application: hd-signin-hrd
version: 2
runtime: python27
threadsafe: true
api_version: 1

inbound_services:
- mail
- channel_presence

builtins:
- appstats: on
- deferred: on

handlers:
- url: /stats.*
  script: google.appengine.ext.appstats.ui.app
- url: /static
  static_dir: static
- url: .*
  script: main.app
  secure: always
