application: hd-signin-hrd
version: 2
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always
- url: /static
  static_dir: static
  secure: always
- url: .*
  script: main.app
  secure: always
