application: hd-signin-hrd
version: 2
runtime: python27
threadsafe: true
api_version: 1

inbound_services:
- mail
- channel_presence

builtins:
- appstats: on
- deferred: on

handlers:
- url: /stats.*
  script: google.appengine.ext.appstats.ui.app
- url: /static
  static_dir: static
#- url: /_ah/queue/deferred
#  script: google.appengine.ext.deferred.handler.app
#  login: admin
- url: .*
  script: main.app
